### PR TITLE
Multipole: turn on CI test

### PR DESCRIPTION
**Pull request by lwJi**

### CODE REVIEW

**Review by rhaas80 — COMMENTED** [review]
Why are the data files being updated? Shouldn't the result be the as before? If not then a comment in the commit message would be good explaining why the change is expected.

**Review by rhaas80 — COMMENTED** [review]
Are these the number the same as for the Carpet based thorn? The file extensions are different and the commit that introduces them  does not really tell anything about whether they have ever been compared to a "known good" version.

**Comment by lwJi** [comment]
> Why are the data files being updated? Shouldn't the result be the as before? If not then a comment in the commit message would be good explaining why the change is expected.

The change is caused by the bug fix in Z4c

**Comment by lwJi** [comment]
> Are these the number the same as for the Carpet based thorn? The file extensions are different and the commit that introduces them does not really tell anything about whether they have ever been compared to a "known good" version.

It was not copied from Carpet. I made it up from scratch. I just want have something that tell me I didn't change the code when I commit

**Comment by rhaas80** [comment]
ok. For the change in values for Multipole's test it may then be good to add something along the lines of:

> Regenerate test data after commit bd461ad4 "Z4c: fix bug related to the misuse of sym_symm"

so that people can correlate the change in Multipole with the source of the changed values.

Best to give both the git hash and the subject line in case we ever move to a different version control system and the git hashes become meaningless (we moved from svn to git for some repo and thankfully git-svn preserves the svn revision numbers as part of the git commit message, but one would not want to rely on that if possible).

**Comment by lwJi** [comment]
> ok. For the change in values for Multipole's test it may then be good to add something along the lines of:
> 
> > Regenerate test data after commit [bd461ad](https://github.com/EinsteinToolkit/SpacetimeX/commit/bd461ad42ad0a6c2c3c2e1ede09ffb3d3927a864) "Z4c: fix bug related to the misuse of sym_symm"
> 
> so that people can correlate the change in Multipole with the source of the changed values.
> 
> Best to give both the git hash and the subject line in case we ever move to a different version control system and the git hashes become meaningless (we moved from svn to git for some repo and thankfully git-svn preserves the svn revision numbers as part of the git commit message, but one would not want to rely on that if possible).

Done

**Review by rhaas80 — APPROVED** [review]

**Pull request merged**
