### PR TITLE
WeylScal4: disable OMP

### PR DESCRIPTION
**Pull request by lwJi**

### CODE REVIEW

**Comment by rhaas80** [comment]
While you are doing this I'd also add the correct support for tiling using the `cctk_tile_min` / `cctk_tile_max` variables.

**Comment by rhaas80** [comment]
commit message might be somewhat confusing for people. possible say "disable omp for" since OpenMP itself is still active (via CarpetX's use of it).

**Review by rhaas80 — CHANGES_REQUESTED** [review]
see comments, when doing this change I'd also add the correct `cctk_tile_min` and `cctk_tile_max` limits (so that the data is not computed multiple times).

**Comment by lwJi** [comment]
> see comments, when doing this change I'd also add the correct `cctk_tile_min` and `cctk_tile_max` limits (so that the data is not computed multiple times).

Done

**Review by rhaas80 — APPROVED** [review]

**Pull request merged**
